/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing20thdec_production.wmstudio.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class SvCustomQueryResponse implements Serializable {


    @ColumnAlias("INT COL")
    private Integer intCol;

    @ColumnAlias("INT ID")
    private Integer intId;

    @ColumnAlias("CHAR COL")
    private String charCol;

    @ColumnAlias("STRING COL")
    private String stringCol;

    public Integer getIntCol() {
        return this.intCol;
    }

    public void setIntCol(Integer intCol) {
        this.intCol = intCol;
    }

    public Integer getIntId() {
        return this.intId;
    }

    public void setIntId(Integer intId) {
        this.intId = intId;
    }

    public String getCharCol() {
        return this.charCol;
    }

    public void setCharCol(String charCol) {
        this.charCol = charCol;
    }

    public String getStringCol() {
        return this.stringCol;
    }

    public void setStringCol(String stringCol) {
        this.stringCol = stringCol;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof SvCustomQueryResponse)) return false;
        final SvCustomQueryResponse svCustomQueryResponse = (SvCustomQueryResponse) o;
        return Objects.equals(getIntCol(), svCustomQueryResponse.getIntCol()) &&
                Objects.equals(getIntId(), svCustomQueryResponse.getIntId()) &&
                Objects.equals(getCharCol(), svCustomQueryResponse.getCharCol()) &&
                Objects.equals(getStringCol(), svCustomQueryResponse.getStringCol());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getIntCol(),
                getIntId(),
                getCharCol(),
                getStringCol());
    }
}
