/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing20thdec_production.wmstudio.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class Procedure2cursorsResponseJobsdata implements Serializable {


    @ColumnAlias("JOB_ID")
    private String jobId;

    @ColumnAlias("JOB_TITLE")
    private String jobTitle;

    @ColumnAlias("MIN_SALARY")
    private Integer minSalary;

    @ColumnAlias("MAX_SALARY")
    private Integer maxSalary;

    public String getJobId() {
        return this.jobId;
    }

    public void setJobId(String jobId) {
        this.jobId = jobId;
    }

    public String getJobTitle() {
        return this.jobTitle;
    }

    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle;
    }

    public Integer getMinSalary() {
        return this.minSalary;
    }

    public void setMinSalary(Integer minSalary) {
        this.minSalary = minSalary;
    }

    public Integer getMaxSalary() {
        return this.maxSalary;
    }

    public void setMaxSalary(Integer maxSalary) {
        this.maxSalary = maxSalary;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Procedure2cursorsResponseJobsdata)) return false;
        final Procedure2cursorsResponseJobsdata procedure2cursorsResponseJobsdata = (Procedure2cursorsResponseJobsdata) o;
        return Objects.equals(getJobId(), procedure2cursorsResponseJobsdata.getJobId()) &&
                Objects.equals(getJobTitle(), procedure2cursorsResponseJobsdata.getJobTitle()) &&
                Objects.equals(getMinSalary(), procedure2cursorsResponseJobsdata.getMinSalary()) &&
                Objects.equals(getMaxSalary(), procedure2cursorsResponseJobsdata.getMaxSalary());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getJobId(),
                getJobTitle(),
                getMinSalary(),
                getMaxSalary());
    }
}
