/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/

package com.testing20thdec_production.hrdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.query.WMQueryExecutor;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testing20thdec_production.hrdb.models.query.*;

@Service
public class HrdbQueryExecutorServiceImpl implements HrdbQueryExecutorService {

    private static final Logger LOGGER = LoggerFactory.getLogger(HrdbQueryExecutorServiceImpl.class);

    @Autowired
    @Qualifier("hrdbWMQueryExecutor")
    private WMQueryExecutor queryExecutor;

    @Transactional(readOnly = true, value = "hrdbTransactionManager")
    @Override
    public Page<SvDeptDataResponse> executeSV_DeptData(Pageable pageable) {
        Map params = new HashMap(0);


        return queryExecutor.executeNamedQuery("SV_DeptData", params, SvDeptDataResponse.class, pageable);
    }

    @Transactional(readOnly = true, value = "hrdbTransactionManager")
    @Override
    public Downloadable exportSV_DeptData(ExportType exportType, Pageable pageable) {
        Map params = new HashMap(0);


        return queryExecutor.exportNamedQueryData("SV_DeptData", params, exportType, SvDeptDataResponse.class, pageable);
    }

    @Transactional(readOnly = true, value = "hrdbTransactionManager")
    @Override
    public Page<HqlListVacationDataResponse> executeHQL_ListVacationData(List<Integer> empid, Pageable pageable) {
        Map params = new HashMap(1);

        params.put("EMPID", empid);

        return queryExecutor.executeNamedQuery("HQL_ListVacationData", params, HqlListVacationDataResponse.class, pageable);
    }

    @Transactional(readOnly = true, value = "hrdbTransactionManager")
    @Override
    public Downloadable exportHQL_ListVacationData(ExportType exportType, List<Integer> empid, Pageable pageable) {
        Map params = new HashMap(1);

        params.put("EMPID", empid);

        return queryExecutor.exportNamedQueryData("HQL_ListVacationData", params, exportType, HqlListVacationDataResponse.class, pageable);
    }

    @Transactional(readOnly = true, value = "hrdbTransactionManager")
    @Override
    public Page<SvListEmpResponse> executeSV_ListEmp(List<Integer> deptid, Pageable pageable) {
        Map params = new HashMap(1);

        params.put("DEPTID", deptid);

        return queryExecutor.executeNamedQuery("SV_ListEmp", params, SvListEmpResponse.class, pageable);
    }

    @Transactional(readOnly = true, value = "hrdbTransactionManager")
    @Override
    public Downloadable exportSV_ListEmp(ExportType exportType, List<Integer> deptid, Pageable pageable) {
        Map params = new HashMap(1);

        params.put("DEPTID", deptid);

        return queryExecutor.exportNamedQueryData("SV_ListEmp", params, exportType, SvListEmpResponse.class, pageable);
    }

}


