/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing20thdec_production.wmstudio;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

public class Many2oneRelationChild1Id implements Serializable {

    private Byte byteId;
    private String stringId;

    public Byte getByteId() {
        return this.byteId;
    }

    public void setByteId(Byte byteId) {
        this.byteId = byteId;
    }

    public String getStringId() {
        return this.stringId;
    }

    public void setStringId(String stringId) {
        this.stringId = stringId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Many2oneRelationChild1)) return false;
        final Many2oneRelationChild1 many2oneRelationChild1 = (Many2oneRelationChild1) o;
        return Objects.equals(getByteId(), many2oneRelationChild1.getByteId()) &&
                Objects.equals(getStringId(), many2oneRelationChild1.getStringId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getByteId(),
                getStringId());
    }
}
