/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing20thdec_production.wmstudio;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.wavemaker.runtime.data.annotations.WMValueInject;
import com.wavemaker.runtime.data.replacers.Scope;
import com.wavemaker.runtime.data.replacers.providers.VariableType;

/**
 * ServerDefinedTable generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`SERVER_DEFINED_TABLE`")
public class ServerDefinedTable implements Serializable {

    private Integer seqId;
    @WMValueInject( type = VariableType.SERVER, name = "USER_ID", scopes = { Scope.INSERT })
    private Short userIdInsertable;
    @WMValueInject( type = VariableType.SERVER, name = "USER_ID", scopes = { Scope.UPDATE })
    private Short userIdUpdatable;
    @WMValueInject( type = VariableType.SERVER, name = "USER_ID", scopes = { Scope.INSERT, Scope.UPDATE })
    private Integer userIdInsertUpdate;
    @WMValueInject( type = VariableType.SERVER, name = "USER_NAME", scopes = { Scope.INSERT })
    private String userNameInsertable;
    @WMValueInject( type = VariableType.SERVER, name = "USER_NAME", scopes = { Scope.UPDATE })
    private String userNameUpdatable;
    @WMValueInject( type = VariableType.SERVER, name = "USER_NAME", scopes = { Scope.INSERT, Scope.UPDATE })
    private String userNameInsertUpdate;
    @WMValueInject( type = VariableType.SERVER, name = "USER_ID", scopes = { Scope.INSERT })
    private String useridStringInsertable;
    @WMValueInject( type = VariableType.SERVER, name = "USER_ID", scopes = { Scope.UPDATE })
    private String useridStringUpdatable;
    @WMValueInject( type = VariableType.SERVER, name = "USER_ID", scopes = { Scope.INSERT, Scope.UPDATE })
    private String useridStringInsertUpdate;
    private String sampleColumn;

    @Id
    @SequenceGenerator(name = "generator", sequenceName = "`INC_BY_5`" , schema = "SARASWATHI", allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
    @Column(name = "`SEQ ID`", nullable = false, scale = 0, precision = 10)
    public Integer getSeqId() {
        return this.seqId;
    }

    public void setSeqId(Integer seqId) {
        this.seqId = seqId;
    }

    @Column(name = "`USER_ID_INSERTABLE`", nullable = true, updatable = false, scale = 0, precision = 5)
    public Short getUserIdInsertable() {
        return this.userIdInsertable;
    }

    public void setUserIdInsertable(Short userIdInsertable) {
        this.userIdInsertable = userIdInsertable;
    }

    @Column(name = "`USER_ID_UPDATABLE`", nullable = true, insertable = false, scale = 0, precision = 5)
    public Short getUserIdUpdatable() {
        return this.userIdUpdatable;
    }

    public void setUserIdUpdatable(Short userIdUpdatable) {
        this.userIdUpdatable = userIdUpdatable;
    }

    @Column(name = "`USER_ID_INSERT_UPDATE`", nullable = true, scale = 0, precision = 10)
    public Integer getUserIdInsertUpdate() {
        return this.userIdInsertUpdate;
    }

    public void setUserIdInsertUpdate(Integer userIdInsertUpdate) {
        this.userIdInsertUpdate = userIdInsertUpdate;
    }

    @Column(name = "`USER_NAME_INSERTABLE`", nullable = true, updatable = false, length = 20)
    public String getUserNameInsertable() {
        return this.userNameInsertable;
    }

    public void setUserNameInsertable(String userNameInsertable) {
        this.userNameInsertable = userNameInsertable;
    }

    @Column(name = "`USER_NAME_UPDATABLE`", nullable = true, insertable = false, length = 20)
    public String getUserNameUpdatable() {
        return this.userNameUpdatable;
    }

    public void setUserNameUpdatable(String userNameUpdatable) {
        this.userNameUpdatable = userNameUpdatable;
    }

    @Column(name = "`USER_NAME_INSERT_UPDATE`", nullable = true, length = 20)
    public String getUserNameInsertUpdate() {
        return this.userNameInsertUpdate;
    }

    public void setUserNameInsertUpdate(String userNameInsertUpdate) {
        this.userNameInsertUpdate = userNameInsertUpdate;
    }

    @Column(name = "`USERID_STRING_INSERTABLE`", nullable = true, updatable = false, length = 255)
    public String getUseridStringInsertable() {
        return this.useridStringInsertable;
    }

    public void setUseridStringInsertable(String useridStringInsertable) {
        this.useridStringInsertable = useridStringInsertable;
    }

    @Column(name = "`USERID_STRING_UPDATABLE`", nullable = true, insertable = false, length = 255)
    public String getUseridStringUpdatable() {
        return this.useridStringUpdatable;
    }

    public void setUseridStringUpdatable(String useridStringUpdatable) {
        this.useridStringUpdatable = useridStringUpdatable;
    }

    @Column(name = "`USERID_STRING_INSERT_UPDATE`", nullable = true, length = 255)
    public String getUseridStringInsertUpdate() {
        return this.useridStringInsertUpdate;
    }

    public void setUseridStringInsertUpdate(String useridStringInsertUpdate) {
        this.useridStringInsertUpdate = useridStringInsertUpdate;
    }

    @Column(name = "`SAMPLE_COLUMN`", nullable = true, length = 255)
    public String getSampleColumn() {
        return this.sampleColumn;
    }

    public void setSampleColumn(String sampleColumn) {
        this.sampleColumn = sampleColumn;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ServerDefinedTable)) return false;
        final ServerDefinedTable serverDefinedTable = (ServerDefinedTable) o;
        return Objects.equals(getSeqId(), serverDefinedTable.getSeqId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getSeqId());
    }
}

