/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing20thdec_production.hrdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Date;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class HqlListVacationDataResponse implements Serializable {


    @ColumnAlias("EMPLOYEE_ID")
    private Integer employeeId;

    @ColumnAlias("START_DATE")
    private Date startDate;

    @ColumnAlias("END_DATE")
    private Date endDate;

    @ColumnAlias("STATUS")
    private String status;

    public Integer getEmployeeId() {
        return this.employeeId;
    }

    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    public Date getStartDate() {
        return this.startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    public Date getEndDate() {
        return this.endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof HqlListVacationDataResponse)) return false;
        final HqlListVacationDataResponse hqlListVacationDataResponse = (HqlListVacationDataResponse) o;
        return Objects.equals(getEmployeeId(), hqlListVacationDataResponse.getEmployeeId()) &&
                Objects.equals(getStartDate(), hqlListVacationDataResponse.getStartDate()) &&
                Objects.equals(getEndDate(), hqlListVacationDataResponse.getEndDate()) &&
                Objects.equals(getStatus(), hqlListVacationDataResponse.getStatus());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getEmployeeId(),
                getStartDate(),
                getEndDate(),
                getStatus());
    }
}
