/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing20thdec_production.schooldb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.List;
import java.util.Map;

import javax.validation.Valid;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.data.periods.PeriodClause;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testing20thdec_production.schooldb.Policynohiddencol;

/**
 * Service object for domain model class {@link Policynohiddencol}.
 */
public interface PolicynohiddencolService {

    /**
     * Creates a new Policynohiddencol. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Policynohiddencol if any.
     *
     * @param policynohiddencol Details of the Policynohiddencol to be created; value cannot be null.
     * @return The newly created Policynohiddencol.
     */
	Policynohiddencol create(@Valid Policynohiddencol policynohiddencol);


	/**
	 * Returns Policynohiddencol by given id if exists.
	 *
	 * @param policynohiddencolId The id of the Policynohiddencol to get; value cannot be null.
	 * @return Policynohiddencol associated with the given policynohiddencolId.
     * @throws EntityNotFoundException If no Policynohiddencol is found.
	 */
	Policynohiddencol getById(Integer policynohiddencolId) throws EntityNotFoundException;

    /**
	 * Find and return the Policynohiddencol by given id if exists, returns null otherwise.
	 *
	 * @param policynohiddencolId The id of the Policynohiddencol to get; value cannot be null.
	 * @return Policynohiddencol associated with the given policynohiddencolId.
	 */
	Policynohiddencol findById(Integer policynohiddencolId);


	/**
	 * Updates the details of an existing Policynohiddencol. It replaces all fields of the existing Policynohiddencol with the given policynohiddencol.
	 *
     * This method overrides the input field values using Server side or database managed properties defined on Policynohiddencol if any.
     *
	 * @param policynohiddencol The details of the Policynohiddencol to be updated; value cannot be null.
	 * @return The updated Policynohiddencol.
	 * @throws EntityNotFoundException if no Policynohiddencol is found with given input.
	 */
	Policynohiddencol update(@Valid Policynohiddencol policynohiddencol) throws EntityNotFoundException;

    /**
	 * Deletes an existing Policynohiddencol with the given id.
	 *
	 * @param policynohiddencolId The id of the Policynohiddencol to be deleted; value cannot be null.
	 * @return The deleted Policynohiddencol.
	 * @throws EntityNotFoundException if no Policynohiddencol found with the given id.
	 */
	Policynohiddencol delete(Integer policynohiddencolId) throws EntityNotFoundException;

	/**
	 * Find all Policynohiddencols matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
	 *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
	 *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Policynohiddencols.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
	 */
    @Deprecated
	Page<Policynohiddencol> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Find all Policynohiddencols matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Policynohiddencols.
     *
     * @see Pageable
     * @see Page
	 */
    Page<Policynohiddencol> findAll(String query, Pageable pageable);

    /**
	 * Find all Policynohiddencols's history matching the given period clauses and query. This method returns
     * Paginated results.
     * Note: Go through the documentation for <u>periodClause</u> and <u>query</u> syntax.
	 *
     * @param systemClause The period clause condition.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Policynohiddencols.
     *
     * @see Pageable
     * @see Page
	 */
    Page<Policynohiddencol> findHistory(String systemClause, String query, Pageable pageable);

    /**
	 * Find all Policynohiddencols's history matching the given period clauses and query. This method returns
     * Paginated results.
     * Note: Go through the documentation for <u>periodClause</u> and <u>query</u> syntax.
	 *
     * @param periodClauses The clauses to filter history.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Policynohiddencols.
     *
     * @see Pageable
     * @see Page
	 */
    Page<Policynohiddencol> findHistory(List<PeriodClause> periodClauses, String query, Pageable pageable);

    /**
	 * Exports all Policynohiddencols matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
	 */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the Policynohiddencols in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
	 * @return The count of the Policynohiddencol.
	 */
	long count(String query);

	/**
	 * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
	 * @return Paginated data with included fields.

     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
	Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}

