/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/

package com.testing20thdec_production.wmstudio.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.util.HashMap;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.servlet.support.ServletUriComponentsBuilder;
import org.springframework.web.util.UriComponentsBuilder;

import com.fasterxml.jackson.annotation.JsonView;
import com.wavemaker.commons.json.views.JsonViews.BlobAsUrlView;
import com.wavemaker.commons.wrapper.IntegerWrapper;
import com.wavemaker.runtime.data.dao.query.WMQueryExecutor;
import com.wavemaker.runtime.data.exception.BlobContentNotFoundException;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.file.model.Downloadable;
import com.wavemaker.runtime.util.WMMultipartUtils;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;

import com.testing20thdec_production.wmstudio.service.WMSTUDIOQueryExecutorService;
import com.testing20thdec_production.wmstudio.models.query.*;

@RestController(value = "WMSTUDIO.QueryExecutionController")
@RequestMapping("/WMSTUDIO/queryExecutor")
@Api(value = "QueryExecutionController", description = "controller class for query execution")
public class QueryExecutionController {

    private static final Logger LOGGER = LoggerFactory.getLogger(QueryExecutionController.class);

    @Autowired
    private WMSTUDIOQueryExecutorService queryService;

    @RequestMapping(value = "/queries/SV_InsertQuery_ServerDef", method = RequestMethod.POST)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "SV_InsertQuery_ServerDef")
    public IntegerWrapper executeSV_InsertQuery_ServerDef(@Valid @RequestPart("wm_data_json") SvInsertQueryServerDefRequest svInsertQueryServerDefRequest, @RequestPart(value = "BLOB_COLUMN") MultipartFile blobColumn, HttpServletRequest _request) {
        LOGGER.debug("Executing named query: SV_InsertQuery_ServerDef");
        svInsertQueryServerDefRequest.setBlobColumn(WMMultipartUtils.toByteArray(blobColumn));
        Integer _result = queryService.executeSV_InsertQuery_ServerDef(svInsertQueryServerDefRequest);
        LOGGER.debug("got the result for named query: SV_InsertQuery_ServerDef, result:{}", _result);
        return new IntegerWrapper(_result);
    }

    @RequestMapping(value = "/queries/SV_CustomQuery", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "Custom Query")
    public Page<SvCustomQueryResponse> executeSV_CustomQuery(Pageable pageable, HttpServletRequest _request) {
        LOGGER.debug("Executing named query: SV_CustomQuery");
        Page<SvCustomQueryResponse> _result = queryService.executeSV_CustomQuery(pageable);
        LOGGER.debug("got the result for named query: SV_CustomQuery, result:{}", _result);
        return _result;
    }

    @ApiOperation(value = "Returns downloadable file for query SV_CustomQuery")
    @RequestMapping(value = "/queries/SV_CustomQuery/export/{exportType}", method = RequestMethod.GET, produces = "application/octet-stream")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Downloadable exportSV_CustomQuery(@PathVariable("exportType") ExportType exportType, Pageable pageable, HttpServletRequest _request) {
        LOGGER.debug("Exporting named query: SV_CustomQuery");

        return queryService.exportSV_CustomQuery(exportType, pageable);
    }

    @RequestMapping(value = "/queries/SV_InsertQuery", method = RequestMethod.POST)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "Insert Query")
    public IntegerWrapper executeSV_InsertQuery(@Valid @RequestPart("wm_data_json") SvInsertQueryRequest svInsertQueryRequest, @RequestPart(value = "BLOB_COLUMN") MultipartFile blobColumn, HttpServletRequest _request) {
        LOGGER.debug("Executing named query: SV_InsertQuery");
        svInsertQueryRequest.setBlobColumn(WMMultipartUtils.toByteArray(blobColumn));
        Integer _result = queryService.executeSV_InsertQuery(svInsertQueryRequest);
        LOGGER.debug("got the result for named query: SV_InsertQuery, result:{}", _result);
        return new IntegerWrapper(_result);
    }

    @JsonView(BlobAsUrlView.class)
    @RequestMapping(value = "/queries/SV_AllTypesData", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "All types Datta")
    public Page<SvAllTypesDataResponse> executeSV_AllTypesData(Pageable pageable, HttpServletRequest _request) {
        LOGGER.debug("Executing named query: SV_AllTypesData");
        Page<SvAllTypesDataResponse> _result = queryService.executeSV_AllTypesData(pageable);
        LOGGER.debug("got the result for named query: SV_AllTypesData, result:{}", _result);
        UriComponentsBuilder _uriBuilder = ServletUriComponentsBuilder.fromRequest(_request);
        _uriBuilder.path("/{intId}/content/{_fieldName_}");
        for(SvAllTypesDataResponse _content : _result.getContent()) {
            Map<String, Object> _properties = new HashMap(2);
            _properties.put("intId", _content.getIntId());
            _properties.put("_fieldName_", "blobCol");
            if(_content.getBlobCol() != null) {
                _content.setBlobCol(_uriBuilder.buildAndExpand(_properties).toUriString().getBytes());
            } else {
                _content.setBlobCol(null);
            }
        }
        return _result;
    }

    @ApiOperation(value = "Retrives the BLOB content for property blobCol in query SV_AllTypesData")
    @RequestMapping(value = "/queries/SV_AllTypesData/{intId}/content/blobCol", method = RequestMethod.GET, produces = "application/octet-stream")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Downloadable getBlobColContentForSV_AllTypesData(@PathVariable("intId") Integer intId, @RequestParam(value="downloadAsAttachment", defaultValue = "false") boolean downloadAsAttachment, HttpServletRequest _request) {
        LOGGER.debug("Executing named query: SV_AllTypesData");

        InputStream _result = queryService.getBlobColContentForSV_AllTypesData(intId);
        return WMMultipartUtils.buildDownloadResponse(_request, _result, downloadAsAttachment);
    }

    @ApiOperation(value = "Returns downloadable file for query SV_AllTypesData")
    @RequestMapping(value = "/queries/SV_AllTypesData/export/{exportType}", method = RequestMethod.GET, produces = "application/octet-stream")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Downloadable exportSV_AllTypesData(@PathVariable("exportType") ExportType exportType, Pageable pageable, HttpServletRequest _request) {
        LOGGER.debug("Exporting named query: SV_AllTypesData");

        return queryService.exportSV_AllTypesData(exportType, pageable);
    }

}


