/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/

package com.testing20thdec_production.schooldb.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.HashMap;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;

import com.wavemaker.runtime.data.dao.query.WMQueryExecutor;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.file.model.Downloadable;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;

import com.testing20thdec_production.schooldb.service.SCHOOLDBQueryExecutorService;
import com.testing20thdec_production.schooldb.models.query.*;

@RestController(value = "SCHOOLDB.QueryExecutionController")
@RequestMapping("/SCHOOLDB/queryExecutor")
@Api(value = "QueryExecutionController", description = "controller class for query execution")
public class QueryExecutionController {

    private static final Logger LOGGER = LoggerFactory.getLogger(QueryExecutionController.class);

    @Autowired
    private SCHOOLDBQueryExecutorService queryService;

    @RequestMapping(value = "/queries/SV_SystemTemporal", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "System Temporal")
    public Page<SvSystemTemporalResponse> executeSV_SystemTemporal(Pageable pageable, HttpServletRequest _request) {
        LOGGER.debug("Executing named query: SV_SystemTemporal");
        Page<SvSystemTemporalResponse> _result = queryService.executeSV_SystemTemporal(pageable);
        LOGGER.debug("got the result for named query: SV_SystemTemporal, result:{}", _result);
        return _result;
    }

    @ApiOperation(value = "Returns downloadable file for query SV_SystemTemporal")
    @RequestMapping(value = "/queries/SV_SystemTemporal/export/{exportType}", method = RequestMethod.GET, produces = "application/octet-stream")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Downloadable exportSV_SystemTemporal(@PathVariable("exportType") ExportType exportType, Pageable pageable, HttpServletRequest _request) {
        LOGGER.debug("Exporting named query: SV_SystemTemporal");

        return queryService.exportSV_SystemTemporal(exportType, pageable);
    }

    @RequestMapping(value = "/queries/SV_BiTemporal", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "Bi Temporal")
    public Page<SvBiTemporalResponse> executeSV_BiTemporal(Pageable pageable, HttpServletRequest _request) {
        LOGGER.debug("Executing named query: SV_BiTemporal");
        Page<SvBiTemporalResponse> _result = queryService.executeSV_BiTemporal(pageable);
        LOGGER.debug("got the result for named query: SV_BiTemporal, result:{}", _result);
        return _result;
    }

    @ApiOperation(value = "Returns downloadable file for query SV_BiTemporal")
    @RequestMapping(value = "/queries/SV_BiTemporal/export/{exportType}", method = RequestMethod.GET, produces = "application/octet-stream")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Downloadable exportSV_BiTemporal(@PathVariable("exportType") ExportType exportType, Pageable pageable, HttpServletRequest _request) {
        LOGGER.debug("Exporting named query: SV_BiTemporal");

        return queryService.exportSV_BiTemporal(exportType, pageable);
    }

}


