/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/

package com.testing20thdec_production.wmstudio.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.InputStream;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testing20thdec_production.wmstudio.models.query.*;

public interface WMSTUDIOQueryExecutorService {

    Integer executeSV_InsertQuery_ServerDef(SvInsertQueryServerDefRequest svInsertQueryServerDefRequest);

    Page<SvCustomQueryResponse> executeSV_CustomQuery(Pageable pageable);

    Downloadable exportSV_CustomQuery(ExportType exportType, Pageable pageable);

    Integer executeSV_InsertQuery(SvInsertQueryRequest svInsertQueryRequest);

    Page<SvAllTypesDataResponse> executeSV_AllTypesData(Pageable pageable);

    InputStream getBlobColContentForSV_AllTypesData(Integer intId) throws EntityNotFoundException;

    Downloadable exportSV_AllTypesData(ExportType exportType, Pageable pageable);

}


