/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/

package com.testing20thdec_production.wmstudio.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.util.HashMap;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.query.WMQueryExecutor;
import com.wavemaker.runtime.data.exception.BlobContentNotFoundException;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testing20thdec_production.wmstudio.models.query.*;

@Service
public class WMSTUDIOQueryExecutorServiceImpl implements WMSTUDIOQueryExecutorService {

    private static final Logger LOGGER = LoggerFactory.getLogger(WMSTUDIOQueryExecutorServiceImpl.class);

    @Autowired
    @Qualifier("WMSTUDIOWMQueryExecutor")
    private WMQueryExecutor queryExecutor;

    @Transactional(value = "WMSTUDIOTransactionManager")
    @Override
    public Integer executeSV_InsertQuery_ServerDef(SvInsertQueryServerDefRequest svInsertQueryServerDefRequest) {
        Map params = new HashMap(13);

        params.put("PK_COLUMN", svInsertQueryServerDefRequest.getPkColumn());
        params.put("SHORT_COLUMN", svInsertQueryServerDefRequest.getShortColumn());
        params.put("FLOAT_COLUMN", svInsertQueryServerDefRequest.getFloatColumn());
        params.put("DOUBLE_COLUMN", svInsertQueryServerDefRequest.getDoubleColumn());
        params.put("BIGINT_COLUMN", svInsertQueryServerDefRequest.getBigintColumn());
        params.put("BIGDEC_COLUMN", svInsertQueryServerDefRequest.getBigdecColumn());
        params.put("CHAR_COLUMN", svInsertQueryServerDefRequest.getCharColumn());
        params.put("BOOLEAN_COLUMN", svInsertQueryServerDefRequest.getBooleanColumn());
        params.put("BOOLEAN_Y_N_COLUMN", svInsertQueryServerDefRequest.getBooleanYNColumn());
        params.put("TIMESTAMP_COLUMN", svInsertQueryServerDefRequest.getTimestampColumn());
        params.put("BLOB_COLUMN", svInsertQueryServerDefRequest.getBlobColumn());
        params.put("TEXT_COLUMN", svInsertQueryServerDefRequest.getTextColumn());
        params.put("CLOB_COLUMN", svInsertQueryServerDefRequest.getClobColumn());

        return queryExecutor.executeNamedQueryForUpdate("SV_InsertQuery_ServerDef", params);
    }

    @Transactional(readOnly = true, value = "WMSTUDIOTransactionManager")
    @Override
    public Page<SvCustomQueryResponse> executeSV_CustomQuery(Pageable pageable) {
        Map params = new HashMap(0);


        return queryExecutor.executeNamedQuery("SV_CustomQuery", params, SvCustomQueryResponse.class, pageable);
    }

    @Transactional(readOnly = true, value = "WMSTUDIOTransactionManager")
    @Override
    public Downloadable exportSV_CustomQuery(ExportType exportType, Pageable pageable) {
        Map params = new HashMap(0);


        return queryExecutor.exportNamedQueryData("SV_CustomQuery", params, exportType, SvCustomQueryResponse.class, pageable);
    }

    @Transactional(value = "WMSTUDIOTransactionManager")
    @Override
    public Integer executeSV_InsertQuery(SvInsertQueryRequest svInsertQueryRequest) {
        Map params = new HashMap(17);

        params.put("PK_COLUMN", svInsertQueryRequest.getPkColumn());
        params.put("BYTE_COLUMN", svInsertQueryRequest.getByteColumn());
        params.put("SHORT_COLUMN", svInsertQueryRequest.getShortColumn());
        params.put("INT_COLUMN", svInsertQueryRequest.getIntColumn());
        params.put("FLOAT_COLUMN", svInsertQueryRequest.getFloatColumn());
        params.put("DOUBLE_COLUMN", svInsertQueryRequest.getDoubleColumn());
        params.put("BIGINT_COLUMN", svInsertQueryRequest.getBigintColumn());
        params.put("BIGDEC_COLUMN", svInsertQueryRequest.getBigdecColumn());
        params.put("CHAR_COLUMN", svInsertQueryRequest.getCharColumn());
        params.put("STRING_COLUMN", svInsertQueryRequest.getStringColumn());
        params.put("BOOLEAN_COLUMN", svInsertQueryRequest.getBooleanColumn());
        params.put("BOOLEAN_Y_N_COLUMN", svInsertQueryRequest.getBooleanYNColumn());
        params.put("DATETIME_COLUMN", svInsertQueryRequest.getDatetimeColumn());
        params.put("TIMESTAMP_COLUMN", svInsertQueryRequest.getTimestampColumn());
        params.put("BLOB_COLUMN", svInsertQueryRequest.getBlobColumn());
        params.put("TEXT_COLUMN", svInsertQueryRequest.getTextColumn());
        params.put("CLOB_COLUMN", svInsertQueryRequest.getClobColumn());

        return queryExecutor.executeNamedQueryForUpdate("SV_InsertQuery", params);
    }

    @Transactional(readOnly = true, value = "WMSTUDIOTransactionManager")
    @Override
    public Page<SvAllTypesDataResponse> executeSV_AllTypesData(Pageable pageable) {
        Map params = new HashMap(0);


        return queryExecutor.executeNamedQuery("SV_AllTypesData", params, SvAllTypesDataResponse.class, pageable);
    }

    @Transactional(readOnly = true, value = "WMSTUDIOTransactionManager")
    @Override
    public InputStream getBlobColContentForSV_AllTypesData(Integer intId) throws EntityNotFoundException {
        Map params = new HashMap(0);

        params.put("intId", intId);

        SvAllTypesDataResponse _result =  queryExecutor.executeNamedQuery("SV_AllTypesData__identifier", params, SvAllTypesDataResponse.class);
        if(_result.getBlobCol() == null) {
            LOGGER.debug("Blob content not exists for blobCol in query SV_AllTypesData");
            throw new BlobContentNotFoundException("Blob content not found for blobCol in query SV_AllTypesData");
        }
        return new ByteArrayInputStream(_result.getBlobCol());
    }

    @Transactional(readOnly = true, value = "WMSTUDIOTransactionManager")
    @Override
    public Downloadable exportSV_AllTypesData(ExportType exportType, Pageable pageable) {
        Map params = new HashMap(0);


        return queryExecutor.exportNamedQueryData("SV_AllTypesData", params, exportType, SvAllTypesDataResponse.class, pageable);
    }

}


